name: hypo-sleep
channels:
- defaults
- conda-forge
- edeno
dependencies:
- "python>=3.11,<3.13"
- pip
- bottleneck
- numpy
- numba
- scipy
- scikit-learn
- scikit-image
- matplotlib
- xarray
- netCDF4
- h5netcdf
- cftime
- cupy
- pandas
- dask
- tqdm
- statsmodels
- jupyter
- jupyterlab>=3.*
- nb_conda
- setuptools
- autopep8
- mat73
- black
- spectral_connectivity
- pyrasa
- neurodsp
- nitime
- pip:
  - "black[jupyter]"
  # - spikeinterface>=0.99.1,<0.100